name: Debug Snyk
 
on:
  workflow_dispatch:
 
jobs:
  snyk:
    runs-on: ubuntu-latest
 
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
    steps:
      - uses: actions/checkout@v4
 
      - uses: snyk/actions/setup@master
 
      - name: Check Snyk Version
        run: snyk --version
 
      - name: Check Authentication
        run: snyk auth $SNYK_TOKEN
 
      - name: Show User
        run: snyk whoami
 
      - name: Run Snyk Code
        run: snyk code test -d
